# Assignment 4_NumPy and Pandas
## Due: Mar. 21st 11:59 PM

In [ ]:
# Group members: Gavin Ellstrom, Grant Mondejar, Anthony Simeone

### 1. Create a 3x3 matrix with positive integers of your choice.

In [13]:
# Your code:
import numpy as np
data = [[2,4,9], [16,25,36], [49,64,81]]
arr = np.array(data)
print(arr)

[[ 2  4  9]
 [16 25 36]
 [49 64 81]]


### 2. Calculate the square root of each element in the 3x3 matrix you created, and display the resulting matrix.

In [14]:
# Your code:
print(arr**0.5)

[[1.41421356 2.         3.        ]
 [4.         5.         6.        ]
 [7.         8.         9.        ]]


### 3. Create the following matrix and perform the operations listed below: <br>
[[12, 23, 45, 21]<br>[45, 67, 34, 90] <br>[11, 12, 13, 14] <br> [54, 67, 78, 34]]
> a. print the second row. <br>
> b. print the third column. <br>
> c. print the element on the second row and third column. <br>
> d. print the mean values across rows and columns. <br>
> e. print the mean values across columns.

In [38]:
# Your code:
data3 = [[12,23,45,21],[45,67,34,90],[11,12,13,14],[54,67,78,34]]
arr3 = np.array(data3)
print(arr3)

print('\na.')
print(arr3[1])

print('\nb.')
print(arr3[:,2:3])

print('\nc.')
print(arr3[1,2])

print('\nd.')
print(np.mean(arr3))

print('\ne.')
print(np.mean(arr3, axis = 0))

[[12 23 45 21]
 [45 67 34 90]
 [11 12 13 14]
 [54 67 78 34]]

a.
[45 67 34 90]

b.
[[45]
 [34]
 [13]
 [78]]

c.
34

d.
38.75

e.
[30.5  42.25 42.5  39.75]


### 4. Considering the following NumPy array, write code to access only the odd numbers (hint: use an arithmetic operator within array indexing). 

### arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]) 

### Desired Output : array([1, 3, 5, 7, 9])

In [41]:
# Your code:
arr4 = np.array([1,2,3,4,5,6,7,8,9])

arr4[arr4 % 2 == 1]

array([1, 3, 5, 7, 9])

### 5.  Create a DataFrame with two columns named "ranking" and "enrollment" for the following Florida colleges. Use the provided national rankings and enrollment numbers for each college:

### National rankings: 
> UF: 30 <br>
> UM: 49 <br>
> FSU: 58 <br>
> USF: 103 <br>
> UCF: 160 <br>
> FIU: 187 <br>

### Enrollment information: 
> UF: 35000 <br>
> UM: 11307 <br>
> FSU: 33270 <br>
> USF: 32681 <br>
> UCF: 59483 <br>
> FIU: 49004 <br>

In [46]:
# Your code:
import pandas as pd

rankings = {"UF": 30, "UM": 49, "FSU": 58, "USF": 103, "UCF": 160, "FIU": 187}
enrollment = {"UF": 35000, "UM": 11307, "FSU": 33270, "USF": 32681, "UCF": 59483, "FIU": 49004}

data5 = pd.DataFrame(rankings)
print(data5)

ValueError: If using all scalar values, you must pass an index

### 6. The enrollment for UF is entered incorrectly. Change the number to 35,405 using iloc or loc method.

In [ ]:
# Your code:


### 7. Generate another column to store in-state tuition amounts. Tuition amounts for these colleges in dollars are given as follows: 
> UF: 6380 <br>
> UM: 53682 <br>
> FSU: 6507 <br>
> USF: 6410 <br>
> UCF: 6368 <br>
> FIU: 6566 <br>

In [ ]:
# Your code:


### 8. Display the colleges in the top 100 with tuition amounts less than $10,000.

In [ ]:
# Your code:
